### PR TITLE
Mod: fixed some issues in config folder that reported by sonar-qube

### LINKED ISSUE #617: Enhancement: gitee quality analyses -- config
**What would you like to be added**:

**Why is this needed**:

### PR DESCRIPTION
**Pull request by williamfeng323**
**What this PR does**:
Fixed the bad smell codes dected by sonarqube
**Which issue(s) this PR fixes**:
Fixes #617

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: config/config_loader.go [hunk 1]
```diff
@@ -89,7 +89,7 @@ func loadConsumerConfig() {
 	// init other consumer config
 	conConfigType := consumerConfig.ConfigType
 	for key, value := range extension.GetDefaultConfigReader() {
-		if conConfigType == nil {
+		if conConfigType != nil {
```
Comment (AlexStocks) [inline config/config_loader.go:92]: r u kidding me? why using "!=" instead of "=="?
