### PR TITLE
Fix: Make the Consumer config property `Check ` available

### LINKED ISSUE #1555: Consumer Level check set to false doesn't work.
version: dubbo-go 3.0.0-rc3

dubbo:
  consumer:
    check: false  # doesn't work

### PR DESCRIPTION
**Pull request by PhilYue**
**What this PR does**:
Make the Consumer config property `Check ` available

**Which issue(s) this PR fixes**:

Fixes #1555 

**Special notes for your reviewer**:

- in the Consumer service, the Reference config property `check` use the Consumer config when omitted.
- cancel default value of the Reference config property `check`

**Does this PR introduce a user-facing change?**:

NONE
```release-note

```

### CODE REVIEW

File: config/reference_config.go [hunk 1]
```diff
@@ -46,7 +46,7 @@ type ReferenceConfig struct {
 	pxy            *proxy.Proxy
 	id             string
 	InterfaceName  string            `required:"true"  yaml:"interface"  json:"interface,omitempty" property:"interface"`
-	Check          *bool             `default:"true" yaml:"check"  json:"check,omitempty" property:"check"`
+	Check          *bool             `yaml:"check"  json:"check,omitempty" property:"check"`
```
Comment (zhaoyunxing92) [inline config/reference_config.go:49]: 为什么要删除default设置

Comment (PhilYue) [reply config/reference_config.go:49]: 为了让 Reference Config 的 check 延用 Consumer Config 的 check 配置，
如果 reference 的 check 有默认值，就没法判断是用户自己配置的还是默认的

**Comment by LaurenceLiZhixin** [comment]
I would merge master to your repo, and ci may pass.

**Review by LaurenceLiZhixin — APPROVED** [review]

**Review by AlexStocks — APPROVED** [review]

**Review by justxuewei — APPROVED** [review]
