### PR TITLE
fix: polaris router support application name

### LINKED ISSUE #3163: [BUG] Polaris router fails to retrieve application name
### ✅ Verification Checklist

- [x] 🔍 I have searched the [existing issues](https://github.com/apache/dubbo-go/issues) and confirmed this is not a duplicate

### 🚀 Go Version

1.24.0

### 📦 Dubbo-go Version

v3.3.1

### 🖥️ Server Configuration

_No response_

### 💻 Client Configuration

_No response_

### 🌐 Protocol Configuration

_No response_

### 📋 Registry Configuration

_No response_

### 💾 Operating System

🐧 Linux

### 📝 Bug Description

When using the new dubbo.NewInstance API to initialize a Dubbo-go application, the Polaris router fails to build the router chain. It reports an error stating that the application name is missing, even though dubbo.WithName("myApp") has been explicitly configured.

### 🔄 Steps to Reproduce

Using the following code to initialize either a consumer or a provider:
```go
polarisAddr := "127.0.0.1:8091"

ins, err := dubbo.NewInstance(
    dubbo.WithName("myApp"),
    dubbo.WithRegistry(
        registry.WithPolaris(),
        registry.WithAddress(polarisAddr),
        registry.WithNamespace("dubbogo"),
        registry.WithRegisterInterface(),
    ),
    dubbo.WithProtocol(
        protocol.WithTriple(),
        protocol.WithPort(21000),
    ),
)
```
The application fails to start with the following error logs:
```bash
2026-01-15 21:29:37  INFO    dubbo-go/options.go:99  [Config Center] Config center doesn't start
2026-01-15 21:29:37  ERROR   chain/chain.go:121      Build router chain failed with routerFactories key:polaris-router and error:polaris router must set application name
```

### ✅ Expected Behavior

The Polaris router should be able to retrieve the application name from the Instance or global configuration, and the router chain should be built successfully.

### ❌ Actual Behavior

```bash
2026-01-15 21:29:37  ERROR   chain/chain.go:121      Build router chain failed with routerFactories key:polaris-router and error:polaris router must set application name
```

### 💡 Possible Solution

_No response_

### PR DESCRIPTION
**Pull request by zbchi**
### Description
Fixes #3163 

#### Root Cause

In the new API workflow, the application name is stored in the attributes of the service URL. However, the Polaris router is initialized using the registry URL during the construction of the router chain. Since the registry URL does not carry the application name information, it fails the validation check in the Polaris router.

#### Solution

Retrieve the application name directly from serviceUrl (the sub-URL of registryUrl)

#### Changes

File: cluster/router/polaris/router.go

 add the following logic to pass the application name:
```go 
	// if not found, try to get from SubURL (registry directory scenario)
	if applicationName == "" {
		applicationName = url.SubURL.GetParam(constant.ApplicationKey, "")
	}
```
### Checklist
- [x] I confirm the target branch is `develop`
- [x] Code has passed local testing
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: cluster/router/polaris/router.go [hunk 1]
```diff
@@ -56,6 +56,25 @@ func newPolarisRouter(url *common.URL) (*polarisRouter, error) {
 	// get from url param
 	applicationName := url.GetParam(constant.ApplicationKey, "")
 
+	// if not found in params, try to get from name key
```
Comment (AlexStocks) [inline cluster/router/polaris/router.go]: 我相信你添加这块逻辑一定是遇到了相关问题，可以补充下测试

File: registry/protocol/protocol.go [hunk 2]
```diff
@@ -151,6 +151,11 @@ func (proto *registryProtocol) Refer(url *common.URL) base.Invoker {
 
 	reg := proto.getRegistry(url)
 
+	// copy application name from service URL to registry URL for routers that need it
```
Comment (AlexStocks) [inline registry/protocol/protocol.go]: 看能否补充一个ut

File: cluster/router/polaris/router.go [hunk 3]
```diff
@@ -53,9 +53,14 @@ var (
...
 	applicationName := url.GetParam(constant.ApplicationKey, "")
 
+	// if not found, try to get from SubURL (registry directory scenario)
+	if applicationName == "" {
+		applicationName = url.SubURL.GetParam(constant.ApplicationKey, "")
+	}
+
 	if applicationName == "" {
 		return nil, fmt.Errorf("polaris router must set application name")
 	}
```
Comment (No-SilverBullet) [inline cluster/router/polaris/router.go]: Writing the same conditional logic here would look strange and be difficult to understand. Your logic checks if the application is empty; if it is, it retrieves the value from the suburl; if it's still empty, it returns an error. I think this can be handled within an if statement.

**Comment by AlexStocks** [comment]
Post-merge review，两个问题：

## 1. `url.SubURL` 可能为 nil，直接解引用会 panic

`cluster/router/polaris/router.go:L58-L63`：

```go
if applicationName == "" {
    applicationName = url.SubURL.GetParam(constant.ApplicationKey, "")  // SubURL 可能 nil
}
```

`SubURL` 是 `*common.URL` 指针类型，虽然在当前 registry directory 场景下通常不为空，但其他路径（如直接构造 URL）调用 `newPolarisRouter` 时会 panic。应该加 nil check：

```go
if applicationName == "" && url.SubURL != nil {
    applicationName = url.SubURL.GetParam(constant.ApplicationKey, "")
}
```

## 2. PR 没有修复根因——attribute vs parameter 存储不匹配

`registry/directory/directory.go:L88-96` 把 `ApplicationConfig` 作为**结构体对象**存到 URL attribute 里：
```go
url.SetAttribute(constant.ApplicationKey, application)  // *global.ApplicationConfig
```

但 polaris router 始终用 `url.GetParam` 读 URL **parameter**（字符串），两者永远对不上。这个 PR 只是多加了一层 `SubURL.GetParam` 的 fallback，如果 SubURL 里也没有 ApplicationKey 参数，问题依然存在。

正确的修法应该同时从 URL attribute 读取 `*global.ApplicationConfig` 对象（codebase 里已有这个 pattern，如 `directory.go:L223`）：

```go
applicationName := url.GetParam(constant.ApplicationKey, "")
if applicationName == "" {
    if appConfRaw, ok := url.GetAttribute(constant.ApplicationKey); ok {
        if appConf, ok := appConfRaw.(*global.ApplicationConfig); ok && appConf != nil {
            applicationName = appConf.Name
        }
    }
}
if applicationName == "" && url.SubURL != nil {
    applicationName = url.SubURL.GetParam(constant.ApplicationKey, "")
    if applicationName == "" {
        if appConfRaw, ok := url.SubURL.GetAttribute(constant.ApplicationKey); ok {
            if appConf, ok := appConfRaw.(*global.ApplicationConfig); ok && appConf != nil {
                applicationName = appConf.Name
            }
        }
    }
}
if applicationName == "" {
    return nil, fmt.Errorf("polaris router must set application name")
}
```

建议开 follow-up PR 修复。
