### PR TITLE
fix: fix nacos deregister when receiving shutdown signal

### LINKED ISSUE #3107: [BUG] Graceful shutdown 时收到 SIGINT / SIGTERM 后未从 Nacos 正常注销服务实例
### ✅ 验证清单

- [x] 🔍 我已经搜索过 [现有 Issues](https://github.com/apache/dubbo-go/issues)，确信这不是重复问题

### 🚀 Go 版本

1.24

### 📦 Dubbo-go 版本

3.3.1

### 🖥️ 服务端配置

_No response_

### 💻 客户端配置

_No response_

### 🌐 协议配置

_No response_

### 📋 注册中心配置

nacos 2.1.2

### 💾 操作系统

🐧 Linux

### 📝 Bug 描述

在使用 **dubbo-go + Nacos** 时，发现一个比较严重的问题：

当服务 **收到 kill / SIGINT / SIGTERM 信号并触发优雅下线流程** 时，
**服务并没有在 Nacos 中正常下线（注销实例）**。

### 🔄 重现步骤

1. 本地启动一个最简单的 **Triple Server**
2. 服务启动成功并成功注册到 Nacos
3. 向服务进程发送 `SIGINT` / `SIGTERM`（例如 `kill -2 pid` 或 Ctrl+C）
4. 服务进程打印如下日志并退出：

```text
Graceful shutdown --- Destroy all registriesConfig
```

5. **在服务完全退出前后，Nacos 控制台中该实例仍然存在**

### ✅ 预期行为

在收到 kill 信号并执行 graceful shutdown 时：

- 服务应当 主动调用 Nacos 的 UnRegister / Deregister 接口
- 实例应当在 Nacos 中及时下线，而不是一直保留直到心跳超时

### ❌ 实际行为

- graceful shutdown 日志正常打印
- 但 Nacos 中的服务实例未被注销
- 实例只能在一段时间后依赖 Nacos 心跳超时被动下线

### 💡 可能的解决方案

本地断点调试发现，在优雅下线过程中，会走到如下代码：

```go
func (s *serviceDiscoveryRegistry) UnRegister(url *common.URL) error {
    if !shouldRegister(url) {
        return nil
    }
    return nil
}
```

从当前实现来看：

* `UnRegister` 方法内部 **并未真正调用 Nacos 的 `UnRegisterService` / `DeregisterInstance`**
* 方法直接返回 `nil`
* 实际上并没有执行任何注销逻辑

看起来 graceful shutdown 的流程 **只销毁了 registry 配置（Destroy all registriesConfig）**，
但并没有真正执行注册中心的反注册操作。

## Questions

1. 目前 dubbo-go 的设计是否是 **依赖注册中心心跳超时**，而不是在 shutdown 时主动注销？
2. 如果是期望主动注销：

   * 这里是否是一个遗漏 / Bug？
   * `UnRegister` 是否应该显式调用 Nacos 的 `UnRegisterService`？
3. 是否有推荐的 **正确优雅下线方式**，可以确保实例在 kill 信号后立刻从 Nacos 下线？

### PR DESCRIPTION
**Pull request by Alanxtl**
fix #3107 
in the previous version `UnRegisterService`, is not invoked at all, this function serves as the deregister hook when receiving shutdown signal. This pr fixes it.

### CODE REVIEW

File: registry/servicediscovery/service_discovery_registry.go [hunk 1]
```diff
@@ -133,13 +134,19 @@ func createInstance(meta *info.MetadataInfo, url *common.URL) registry.ServiceIn
 }
 
 func (s *serviceDiscoveryRegistry) UnRegisterService() error {
-	return s.serviceDiscovery.Unregister(s.instance)
+	for _, v := range s.instances {
+		if err := s.serviceDiscovery.Unregister(v); err != nil {
+			return err
+		}
+	}
```
Comment (1kasa) [inline registry/servicediscovery/service_discovery_registry.go:153]: Shouldn't we set this to nil? s.instances = nil

**Comment by 1kasa** [comment]
Looking at it this way, the previous logic seems a bit strange. Our application level supports multiple instance registrations, for example, the service needs to support both the Dubbo protocol and Triple, but it doesn't support unified deregistration?

File: registry/servicediscovery/service_discovery_registry.go (hunk 1 above)
Comment (Alanxtl) [reply registry/servicediscovery/service_discovery_registry.go:153]: done, 我改成了这样：
```go
func (s *serviceDiscoveryRegistry) UnRegisterService() error {
	var (
		keep = s.instances[:0]
		errs []error
	)

	for _, v := range s.instances {
		if err := s.serviceDiscovery.Unregister(v); err != nil {
			// fail to unregister
			keep = append(keep, v)
			errs = append(errs, err)
		}
	}

	s.instances = keep
	return errors.Join(errs...)
}
```

**Comment by Alanxtl** [comment]
> Looking at it this way, the previous logic seems a bit strange. Our application level supports multiple instance registrations, for example, the service needs to support both the Dubbo protocol and Triple, but it doesn't support unified deregistration?

是支持统一的方式unregister的，在`UnRegisterService`函数里面调用的`s.serviceDiscovery.Unregister(v)`函数实际上就是调用对应注册中心的`Unregister`方法，只不过在之前`UnRegisterService`函数根本没有被调用，而且`serviceDiscoveryRegistry`的`instances`成员根本没有被修改

**Review by 1kasa — APPROVED** [review]

File: registry/servicediscovery/service_discovery_registry.go [hunk 2]
```diff
@@ -133,14 +137,31 @@ func createInstance(meta *info.MetadataInfo, url *common.URL) registry.ServiceIn
 }
 
 func (s *serviceDiscoveryRegistry) UnRegisterService() error {
-	return s.serviceDiscovery.Unregister(s.instance)
+	s.lock.Lock()
+	defer s.lock.Unlock()
```
Comment (No-SilverBullet) [inline registry/servicediscovery/service_discovery_registry.go]: the lock is acquired and then the unregister operation is performed. Unregistering involves synchronously calling the registry center's （nacos, zk....）API via the network. Could this lead to the lock being held for too long, impacting performance? just a suggestion you can evaluate it.

**Review by No-SilverBullet — APPROVED** [review]

File: registry/servicediscovery/service_discovery_registry.go (hunk 2 above)
Comment (Alanxtl) [reply registry/servicediscovery/service_discovery_registry.go]: done, 我改成了这样：
```go
func (s *serviceDiscoveryRegistry) UnRegisterService() error {
	s.lock.Lock()
	keep := s.instances[:0]
	origin := s.instances[:]
	s.lock.Unlock()

	var errs []error

	for _, v := range origin {
		if err := s.serviceDiscovery.Unregister(v); err != nil {
			// fail to unregister
			keep = append(keep, v)
			errs = append(errs, err)
		}
	}

	s.lock.Lock()
	s.instances = keep
	s.lock.Unlock()
	return errors.Join(errs...)
}
```
