### PR TITLE
fix(router): call BuildRouterChain method when creating directory.

### LINKED ISSUE #3222: [BUG] 创建staticDirectory的时候routerChain未完全初始化
### ✅ 验证清单

- [x] 🔍 我已经搜索过 [现有 Issues](https://github.com/apache/dubbo-go/issues)，确信这不是重复问题

### 🚀 Go 版本

1.24

### 📦 Dubbo-go 版本

v3.3.2

### 🖥️ 服务端配置

dubbo-go v3.3.2

### 💻 客户端配置

dubbo-go v3.3.2

### 🌐 协议配置

Triple

### 📋 注册中心配置

nil

### 💾 操作系统

🍎 macOS

### 📝 Bug 描述

不使用注册中心的时候会使用staticDirectory，其routerChain后续进行初始化的时候未传入具体的router，导致router功能失效。

### 🔄 重现步骤

No response

### ✅ 预期行为

No response

### ❌ 实际行为

No response

### 💡 可能的解决方案

_No response_

### PR DESCRIPTION
**Pull request by yangpixi**
### Description

Fixes #3222

Call BuildRouterChain method when creating static directory to ensure router capabilities work properly.
Currently, dubbo-go does not support static router configuration, **with the exception of the Tag Router**. (Pending #3219 to support this).

### Checklist
- [x] I confirm the target branch is `develop`
- [x] Code has passed local testing
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: cluster/directory/static/directory.go [hunk 1]
```diff
@@ -45,7 +47,14 @@ func NewDirectory(invokers []protocolbase.Invoker) *directory {
 		invokers:  invokers,
 	}
 
-	dir.RouterChain().SetInvokers(invokers)
+	err := dir.BuildRouterChain(invokers, url)
+	if err != nil {
+		logger.Error(err)
+		if routerChain := dir.RouterChain(); routerChain != nil {
+			routerChain.SetInvokers(invokers)
```
Comment (Alanxtl) [inline cluster/directory/static/directory.go]: 如果routerChain == nil是不是需要log一下

Comment (yangpixi) [reply cluster/directory/static/directory.go]: 这里貌似还有点问题，我再考虑下

File: cluster/directory/static/directory.go [hunk 2]
```diff
@@ -50,9 +50,7 @@ func NewDirectory(invokers []protocolbase.Invoker) *directory {
 	err := dir.BuildRouterChain(invokers, url)
 	if err != nil {
 		logger.Error(err)
-		if routerChain := dir.RouterChain(); routerChain != nil {
-			routerChain.SetInvokers(invokers)
-		}
+		dir.RouterChain().SetInvokers(invokers)
```
Comment (AlexStocks) [inline cluster/directory/static/directory.go:53]: 没看出来这行改动的意义

Comment (yangpixi) [reply cluster/directory/static/directory.go:53]: 如果BuildRouterChain失败了，dir里面的routerChain就是nil，触发不了if语句了
