### PR TITLE
fix(triple): make protocol initialization and invoker tracking race-safe

### LINKED ISSUE #3304: [BUG] Triple 高并发创建 client/service 时存在 data race
### ✅ 验证清单

- [x] 🔍 我已经搜索过 [现有 Issues](https://github.com/apache/dubbo-go/issues)，确信这不是重复问题

### 🚀 Go 版本

go1.26.1 darwin/arm64

### 📦 Dubbo-go 版本

dubbo.apache.org/dubbo-go/v3@v3.3.2-20260419

### 🖥️ 服务端配置

Dubbo-go v3.3.2-20260419  本地 Triple provider： 
- address: 127.0.0.1:20450 
- service: greet.GreetService 
- 用于 retry / high concurrency / race detector 验证

### 💻 客户端配置

Dubbo-go v3.3.2-20260419  本地 high-concurrency client test： - 多个 goroutine 并发创建 Triple client - 通过生成代码调用 retry/proto.NewGreetService() - 使用 explicit URL: tri://127.0.0.1:20450 - 运行 go test -race

### 🌐 协议配置

Triple

### 📋 注册中心配置

无注册中心。  测试使用 explicit Triple URL： tri://127.0.0.1:20450

### 💾 操作系统

🍎 macOS

### 📝 Bug 描述

在使用 `dubbo.apache.org/dubbo-go/v3@v3.3.2-20260419` 对 retry / Triple 路径做高并发和 `go test -race` 验证时，race detector 报告 data race。

普通 retry failure matrix 可以通过，但在多个 goroutine 并发创建 Triple client / service 或并发调用 Triple protocol 初始化路径时，会触发共享状态竞争。

影响范围：
- Triple protocol 初始化
- 并发创建 client / service
- BaseProtocol invoker list 更新
- 高并发测试和真实业务中动态创建客户端的场景

### 🔄 重现步骤

1. 启动一个本地 Triple provider，例如：
   - address: `127.0.0.1:20450`
   - service: `greet.GreetService`

2. 编写一个 high-concurrency Go test：
   - 启动多个 goroutine；
   - 每个 goroutine 创建 Triple client；
   - 通过 generated client 调用 `retry/proto.NewGreetService()`；
   - explicit URL 使用 `tri://127.0.0.1:20450`。

3. 使用 race detector 运行测试：

```bash
go test -race
```

4. 观察 race detector 输出。

### ✅ 预期行为

1. Triple protocol 初始化应是并发安全的。
2. 多个 goroutine 并发创建 client / service 时不应出现 data race。
3. `BaseProtocol` 内部 invoker list 的 Set/Get 操作应避免并发读写竞争。
4. `go test -race` 不应报告读写竞争。
5. retry / timeout / failure matrix 在高并发下应保持语义稳定，且不出现 nil panic 或非预期最终错误。

### ❌ 实际行为

`go test -race` 报告 data race。

第一类竞争发生在 Triple protocol 单例初始化：

```text
WARNING: DATA RACE
Read at ... by goroutine 48:
  dubbo.apache.org/dubbo-go/v3/protocol/triple.GetProtocol()
      .../dubbo-go/v3@v3.3.2-20260419/protocol/triple/triple.go:208

Previous write at ... by goroutine 60:
  dubbo.apache.org/dubbo-go/v3/protocol/triple.GetProtocol()
      .../dubbo-go/v3@v3.3.2-20260419/protocol/triple/triple.go:209
```

第二类竞争发生在 `BaseProtocol.SetInvokers()`：

```text
WARNING: DATA RACE
Read at ... by goroutine 54:
  dubbo.apache.org/dubbo-go/v3/protocol/base.(*BaseProtocol).SetInvokers()
      .../dubbo-go/v3@v3.3.2-20260419/protocol/base/base_protocol.go:70
  dubbo.apache.org/dubbo-go/v3/protocol/triple.(*TripleProtocol).Refer()
      .../dubbo-go/v3@v3.3.2-20260419/protocol/triple/triple.go:162

Previous write at ... by goroutine 60:
  dubbo.apache.org/dubbo-go/v3/protocol/triple.NewTripleProtocol()
      .../dubbo-go/v3@v3.3.2-20260419/protocol/triple/triple.go:202
  dubbo.apache.org/dubbo-go/v3/protocol/triple.GetProtocol()
      .../dubbo-go/v3@v3.3.2-20260419/protocol/triple/triple.go:209
```

测试最终报告：

```text
race detected during execution of test
```

普通 retry failure matrix 本身可以通过，因此这不是 retry 业务语义失败，而是 Triple / BaseProtocol 的并发安全问题。

### 💡 可能的解决方案

建议检查 Triple protocol 和 BaseProtocol 的共享状态访问：

1. Triple protocol singleton 初始化需要并发安全保护，例如：
   - `sync.Once`
   - mutex
   - 或其他明确的 lazy init 同步机制

2. `BaseProtocol` 内部 invoker list / map 的 Set/Get 需要并发安全保护，例如：
   - mutex
   - `sync.Map`
   - copy-on-write
   - 初始化阶段与运行阶段状态隔离

3. 增加 race detector 测试覆盖：
   - 并发创建 Triple client
   - 并发创建 Triple service
   - provider 中途退出 / 重启
   - 高并发 retry

4. 修复时需要注意兼容性，不应改变：
   - method lookup 行为
   - timeout / retry / error propagation 语义
   - Triple 协议调用语义

### PR DESCRIPTION
**Pull request by mochengqian**
### Description
Fixes #3304.

This PR removes data races in the Triple protocol initialization path and the shared `BaseProtocol` invoker tracking path.

## Why

When Triple clients/services are created concurrently, `go test -race` can report races in two places:

1. `triple.GetProtocol()` lazily initializes the global Triple protocol singleton without synchronization.
2. `BaseProtocol.SetInvokers()` appends to the shared invoker slice while other goroutines may read or destroy the same slice.

The second issue is not only a race detector warning. Concurrent appends can also lose invoker references, which can affect lifecycle cleanup.

## How

- Protect Triple protocol singleton initialization with `sync.Once`.
- Add an internal `RWMutex` for `BaseProtocol` invoker list access.
- Make `Invokers()` return a snapshot instead of exposing the internal slice.
- Make `Destroy()` snapshot and clear invokers under lock, then destroy invokers outside the lock.
- Add race regression tests for concurrent Triple protocol initialization and concurrent BaseProtocol invoker access.
- Fix the Triple health-watch test helper to avoid unsynchronized test-only slice access, so package-level race verification stays clean.

## Compatibility

This PR does not change Triple RPC semantics, method lookup behavior, retry/timeout/error propagation, serialization, or public protocol contracts.

The only intentional behavior tightening is that `Invokers()` now returns a snapshot instead of the internal slice, preventing external callers from mutating shared protocol state.

## Tests
go test -race ./protocol/base -count=1
go test -race ./protocol/triple -count=1
go test ./protocol/base ./protocol/triple -count=1
go test ./protocol/dubbo ./protocol/dubbo3 ./protocol/grpc ./protocol/jsonrpc ./protocol/rest -count=1
go test ./server -run TestTripleCaseInsensitiveRoute -count=1
go vet ./protocol/base ./protocol/triple
git diff --check

### Checklist
- [x] I confirm the target branch is `develop`
- [x] Code has passed local testing
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: protocol/base/base_protocol.go [hunk 1]
```diff
@@ -87,13 +97,19 @@ func (bp *BaseProtocol) Refer(url *common.URL) Invoker {
 
 // Destroy will destroy all invoker and exporter, so it only is called once.
 func (bp *BaseProtocol) Destroy() {
+	// Do not hold invokersLock while calling Invoker.Destroy(); implementations may run protocol callbacks.
+	bp.invokersLock.Lock()
+	invokers := make([]Invoker, len(bp.invokers))
+	copy(invokers, bp.invokers)
+	bp.invokers = nil
```
Comment (Alanxtl) [inline protocol/base/base_protocol.go]: 这里为什么是置为nil而不是[]Invoker{}

Comment (mochengqian) [reply protocol/base/base_protocol.go]: Good catch! nil 和 []Invoker{} 对当前核心行为几乎等价：len == 0、range 安全、后续 append 都正常,仔细想了想确实是不必要修改.我将把 nil 还原回 []Invoker{}.

**Review by Alanxtl — APPROVED** [review]
lgtm

**Review by CAICAIIs — APPROVED** [review]

**Review by nanjiek — APPROVED** [review]
lgtm

**Review by AlexStocks — APPROVED** [review]
