### PR TITLE
Fix: #734 

### LINKED ISSUE #734: 启动dubbo-go 服务过段时间zk的监听会报错，但是貌似不影响服务调用
**What happened**:
2020-09-03T17:33:28.149+0800    ?[31mERROR?[0m  zookeeper/client.go:589 zk.Children(path{}) = error(zk: invalid path)
github.com/apache/dubbo-go/common/logger.Errorf
        C:/Users/MST/go/pkg/mod/github.com/apache/dubbo-go@v1.5.1/common/logger/logging.go:52
github.com/apache/dubbo-go/remoting/zookeeper.(*ZookeeperClient).GetChildren
        C:/Users/MST/go/pkg/mod/github.com/apache/dubbo-go@v1.5.1/remoting/zookeeper/client.go:589
github.com/apache/dubbo-go/remoting/zookeeper.(*ZkEventListener).handleZkNodeEvent
        C:/Users/MST/go/pkg/mod/github.com/apache/dubbo-go@v1.5.1/remoting/zookeeper/listener.go:135
github.com/apache/dubbo-go/remoting/zookeeper.(*ZkEventListener).listenDirEvent
        C:/Users/MST/go/pkg/mod/github.com/apache/dubbo-go@v1.5.1/remoting/zookeeper/listener.go:325
github.com/apache/dubbo-go/remoting/zookeeper.(*ZkEventListener).ListenServiceEvent.func1
        C:/Users/MST/go/pkg/mod/github.com/apache/dubbo-go@v1.5.1/remoting/zookeeper/listener.go:357
2020-09-03T17:33:28.150+0800    ?[31mERROR?[0m  zookeeper/listener.go:146       path{} child nodes changed, zk.Children() = error{zk.Children(path:): zk: invalid path}
github.com/apache/dubbo-go/common/logger.Errorf
        C:/Users/MST/go/pkg/mod/github.com/apache/dubbo-go@v1.5.1/common/logger/logging.go:52
github.com/apache/dubbo-go/remoting/zookeeper.(*ZkEventListener).handleZkNodeEvent
        C:/Users/MST/go/pkg/mod/github.com/apache/dubbo-go@v1.5.1/remoting/zookeeper/listener.go:146
github.com/apache/dubbo-go/remoting/zookeeper.(*ZkEventListener).listenDirEvent
        C:/Users/MST/go/pkg/mod/github.com/apache/dubbo-go@v1.5.1/remoting/zookeeper/listener.go:325
github.com/apache/dubbo-go/remoting/zookeeper.(*ZkEventListener).ListenServiceEvent.func1
        C:/Users/MST/go/pkg/mod/github.com/apache/dubbo-go@v1.5.1/remoting/zookeeper/listener.go:357

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by wenxuwan**
**What this PR does**:

try to fix #734 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by zouyx — APPROVED** [review]

File: remoting/zookeeper/listener.go [hunk 1]
```diff
@@ -322,7 +322,7 @@ func (l *ZkEventListener) listenDirEvent(conf *common.URL, zkPath string, listen
 		for {
 			select {
 			case <-ticker.C:
-				l.handleZkNodeEvent(zkEvent.Path, children, listener)
+				l.handleZkNodeEvent(zkPath, children, listener)
```
Comment (AlexStocks) [inline remoting/zookeeper/listener.go:325]: pls add the issue as the comment here

Comment (wenxuwan) [reply remoting/zookeeper/listener.go:325]: try to fix issue #734

**Review by AlexStocks — APPROVED** [review]

**Review by Patrick0308 — APPROVED** [review]
