### PR TITLE
 Imp:improve config & upgrade getty & add connect timeout

### LINKED ISSUE #102: 多个dubbo provider场景，如果某一个provider网络不可达，不会进行自动切换
**What happened**:
当多个dubbo provider的场景下，若有某一个网络不可达，同时客户端进行尝试连接，返回
net.DialTimeout(addr xxx:, timeout:3e+09) = error:dial tcp xxx: i/o timeout，并且不会进行自动的轮询切换
**What you expected to happen**:
当多个dubbo provider的场景下，consumer发起请求时，若有部分provider不可达(无论是网络原因还是provider自身的原因)，consumer应自动切换，并尝试连接别的provider
**How to reproduce it (as minimally and precisely as possible)**:
1. 提供多个dubbo provider场景
2. 可以禁用其中的某一个（达到不可达的目的）
3. consumer发起请求，当请求到达被禁用的provider节点的时候，一直显示i/o timeout，并且不会进行自动的轮询切换
dubbo providers :
dubbo_multi_providers
client timeout：
client_timeout

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by fangyincheng**
**What this PR does**:

  - improve config to be used better
  - upgrade getty version
  - add connect timeout to prevent waiting when the IP is not connected

**Which issue(s) this PR fixes**:

Fixes #102 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

File: protocol/dubbo/client.go [hunk 1]
```diff
@@ -260,7 +207,7 @@ func (c *Client) call(ct CallType, addr string, svcUrl common.URL, method string
 	}
 
 	select {
-	case <-time.After(opts.ResponseTimeout):
+	case <-time.After(c.opts.RequestTimeout):
```
Comment (AlexStocks) [inline protocol/dubbo/client.go]: use getty wheel timer

Comment (fangyincheng) [reply protocol/dubbo/client.go]: ok
