### PR TITLE
fix(protocol): fix panic caused by race condition during invoker destruction

### LINKED ISSUE #3153: [BUG] 多次重新构建ReferenceConfig 会发生panic
### ✅ 验证清单

- [x] 🔍 我已经搜索过 [现有 Issues](https://github.com/apache/dubbo-go/issues)，确信这不是重复问题

### 🚀 Go 版本

1.24

### 📦 Dubbo-go 版本

3.3.1

### 💾 操作系统

🪟 Windows

### 📝 Bug 描述

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102a668f8]

goroutine 3809079 [running]:
dubbo.apache.org/dubbo-go/v3/common.(*URL).GetParam(0x0, {0x1045bd638, 0xb}, {0x0, 0x0})
	/Users/dev/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.3.1/common/url.go:608 +0x38
dubbo.apache.org/dubbo-go/v3/cluster/router/tag.(*PriorityRouter).Notify(0x1414fe18c60, {0x140b6945170, 0x1, 0x1})
	/Users/dev/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.3.1/cluster/router/tag/router.go:80 +0x84
dubbo.apache.org/dubbo-go/v3/cluster/router/chain.(*RouterChain).SetInvokers(0x140f6b38720, {0x140b6945170, 0x1, 0x1})
	/Users/dev/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.3.1/cluster/router/chain/chain.go:95 +0x1a4
dubbo.apache.org/dubbo-go/v3/registry/directory.(*RegistryDirectory).setNewInvokers(0x140b0e65d90)
	/Users/dev/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.3.1/registry/directory/directory.go:344 +0x148
dubbo.apache.org/dubbo-go/v3/registry/directory.(*RegistryDirectory).refreshInvokers(0x140b0e65d90, 0x1416408ea80)
	/Users/dev/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.3.1/registry/directory/directory.go:241 +0x1b4
dubbo.apache.org/dubbo-go/v3/registry/directory.(*RegistryDirectory).Notify(0x140b0e65d90, 0x1416408ea80)
	/Users/dev/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.3.1/registry/directory/directory.go:219 +0x44
dubbo.apache.org/dubbo-go/v3/registry.(*BaseRegistry).Subscribe(0x14000ab90e0, 0x140b14d61c0, {0x104f49fd0, 0x140b0e65d90})
	/Users/dev/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.3.1/registry/base_registry.go:354 +0x44c
dubbo.apache.org/dubbo-go/v3/registry/directory.(*RegistryDirectory).Subscribe.func1()
	/Users/dev/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.3.1/registry/directory/directory.go:167 +0x8c
created by dubbo.apache.org/dubbo-go/v3/registry/directory.(*RegistryDirectory).Subscribe in goroutine 1640288
	/Users/dev/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.3.1/registry/directory/directory.go:165 +0x160
```

升级了3.3.1，开100个协程，每个协程都for循环调用服务，同时代码中定时调用ReferenceConfig.GetInvoker().Destroy()，使代码可以重新构建ReferenceConfig。运行一段时间出现上述问题。

### PR DESCRIPTION
**Pull request by HGD-coder**
### Description
Fixes #3153

#### 1. The Issue (Race Condition)
As described in #3153, a panic (`runtime error: invalid memory address`) occurs under high concurrency when `ReferenceConfig.Destroy()` is triggered:
1. `Destroy()` sets `bi.url = nil` to release resources.
2. Concurrent calls to `GetURL()` return `nil`.
3. Upper layers (Router, LoadBalance, Cluster, Filter) access methods on the returned `nil` URL (e.g., `url.GetParam()`), causing the panic.

#### 2. Solution: Null Object Pattern
This PR introduces a **Null Object Pattern** to fix the panic safely:
- **Global Sentinel**: Adds a thread-safe `emptyURL` initialized via `common.NewURLWithOptions`.
- **Safe Access**: Modifies `GetURL()` to return `emptyURL` instead of `nil` when `bi.url` is destroyed.

#### 3. Why we chose this solution (Comparison of Alternatives)
We evaluated three potential solutions. Here is why the Null Object Pattern is the best choice:

**Option A: Remove `bi.url = nil` in Destroy()**
- **Idea**: Keep the old URL even after destruction.
- **Problem**: This creates **"Zombie Invokers"**. Upper layers would still see a valid Protocol/Host/Port and continue routing traffic to a closed client, causing `use of closed network connection` errors. It also prevents the URL (and its large Map) from being GC'd, causing potential **memory leaks**.

**Option B: Add `if url != nil` checks at every call site**
- **Idea**: Modify all callers (Router, Cluster, LoadBalance, etc.) to check for nil.
- **Problem (Unfeasible)**:
    - **"Whac-A-Mole" Risk**: `GetURL()` is a fundamental method used in **50+ files**. Missing just one spot means the panic persists.
    - **Maintenance Nightmare**: It forces every future developer to remember "Check for nil after GetURL", increasing cognitive load.

**Option C: Null Object Pattern (This PR)**
- **Result**: `GetURL()` never returns nil.
- **Benefit**: Callers don't need to change. The `emptyURL` returns empty parameters, so upper layers (like Router) will naturally filter out this destroyed invoker (e.g., matching params fails gracefully).
- **Cost**: Negligible memory (**~429 Bytes** singleton, verified by benchmark).

#### 4. Verification
| Approach | Bug #3153 Reproduction | Result |
| :--- | :--- | :--- |
| **Null Object (This PR)** | **Passed** (No Panic) | ✅ **Safe & Clean**. Logic remains correct (invoker is treated as empty/unavailable). |
| Remove `url=nil` | Passed (No Panic) | ❌ **Unsafe**. Risk of traffic routing to closed connections (Zombies). |

#### 5. Request for Review
I have verified that this change passes the reproduction script for #3153.
**Could reviewers please help check if introducing this `emptyURL` (Null Object) might have any unexpected side effects on other modules (e.g., Service Discovery or Metrics)?**

### Checklist
- [x] I confirm the target branch is `develop`
- [x] Code has passed local testing
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Alanxtl** [comment]
加一下bug发生场景的test case

File: protocol/base/base_invoker.go [hunk 1]
```diff
@@ -71,6 +74,9 @@ func NewBaseInvoker(url *common.URL) *BaseInvoker {
 
 // GetURL gets base invoker URL
 func (bi *BaseInvoker) GetURL() *common.URL {
+	if bi.url == nil {
+		return emptyURL
+	}
 	return bi.url
 }
```
Comment (Alanxtl) [inline protocol/base/base_invoker.go:85]: 这个函数现在向上层返回一个 `"empty"` 其他调用者看到这个 `"empty"` 之后行为是什么样的呀，能不能贴个代码出来举个例子

比如 Router / LoadBalance 是否按预期将这个 invoker 视为不可用，而不是默默继续使用？

**Comment by Alanxtl** [comment]
我觉得这个方法还是太不优雅了，因为上游对于url为nil时候的处理是不一样的，简单粗暴的返回一个空链接我个人觉得不好

只在发生panic的那个上游加一个对于nil的检测可以吗，GetURL这个函数这样改

**Comment by HGD-coder** [comment]
image
image


> 我觉得这个方法还是太不优雅了，因为上游对于url为nil时候的处理是不一样的，简单粗暴的返回一个空链接我个人觉得不好
> 
> 只在发生panic的那个上游加一个对于nil的检测可以吗，GetURL这个函数这样改

1.太多地方用到GetURL()了，它们都是在Destory()增加url=nil前写的。只修改部分未来是否还有风险？
2.这一次panic是一个调用链中多处偶发（protocol/base/rpc_status.go内的invoker.GetURL().Key()和cluster/router/chain/chain.go的invoker.GetURL().ServiceKey()等），一路上用到的GetURL有点多，并不是修改一个上游，我之前尝试过增加url判空。但是碰到下面这种代码，或者说其他我本来就不清楚机制的代码，并不是加一层过滤就能解决，我自己擅自修改，可能引入其他的bug，我感觉改的越多，错的概率越大。
```go
// cluster/router/chain/chain.go
// Route Loop routers in RouterChain and call Route method to determine the target invokers list.
func (c *RouterChain) Route(url *common.URL, invocation base.Invocation) []base.Invoker {
	finalInvokers := make([]base.Invoker, 0, len(c.invokers))
	// multiple invoker may include different methods, find correct invoker otherwise
	// will return the invoker without methods
	for _, invoker := range c.invokers {
		//假设在这里加了url判空
		if invoker.GetURL().ServiceKey() == url.ServiceKey() {
			finalInvokers = append(finalInvokers, invoker)
		}
	}

	// 【危险】因为上面没选出人来，系统决定“死马当活马医”
	// 强制把原始列表（包含那个url==nil的invoker）赋值回来
	if len(finalInvokers) == 0 {
		finalInvokers = c.invokers
	}

	for _, r := range c.copyRouters() {
		finalInvokers = r.Route(finalInvokers, url, invocation)
	}
	return finalInvokers
}
```

**Comment by Alanxtl** [comment]
你举的这个例子，如果返回一个“empty”不也是一样的结果吗

**Comment by HGD-coder** [comment]
image

我想着用空对象，就是原来的代码应该都有对于url内存在各种内容的匹配。这个示例代码只是说明url=nil的判断可能需要额外的代原始逻辑变更，或者过滤需要在每一层实现；但是空对象在这个情况下和正常对象一样到了下一层，它在下一层不会因为再调用url的方法报panic。但是具体的底层我并不清楚，因为我不知道引入空对象内部的空值会不会和之前的defaultvalue重合判断，所以我希望有经验或者了解底层的人帮忙看看。

**Comment by HGD-coder** [comment]
> image image 我想着用空对象，就是原来的代码应该都有对于url内存在各种内容的匹配。这个示例代码只是说明url=nil的判断可能需要额外的代原始逻辑变更，或者过滤需要在每一层实现；但是空对象在这个情况下和正常对象一样到了下一层，它在下一层不会因为再调用url的方法报panic。但是具体的底层我并不清楚，因为我不知道引入空对象内部的空值会不会和之前的defaultvalue重合判断，所以我希望有经验或者了解底层的人帮忙看看。

**Review by No-SilverBullet — APPROVED** [review]
LGTM

File: protocol/base/base_invoker.go [hunk 2]
```diff
@@ -35,7 +35,14 @@ import (
 	"dubbo.apache.org/dubbo-go/v3/protocol/result"
 )
 
+const (
+	protocolDestroyed = "dubbo-internal-destroyed"
```
Comment (AlexStocks) [inline protocol/base/base_invoker.go]: 改成 “dubbo-go-internal-invoker-distroyed” 吧

**Comment by AlexStocks** [comment]
这个 PR 确实比 https://github.com/apache/dubbo-go/pull/3191 更优雅一些，但是需要更广泛的考虑下其他地方也跟着修改下

**Comment by AlexStocks** [comment]
> lgtm

你 LGTM，那就是先把这个 PR 合并，其他受影响的地方后面再提 PR 吗？

**Review by AlexStocks — APPROVED** [review]
