### PR TITLE
Fix: zk lost event

### LINKED ISSUE #660: Data in cache  is not synchronized after the provider updates in zk
Hi all 

I meet an problem, i update my provider service, but the dubbo-go still try to make connection with old provider address.

the old ip address is different with new ip.

After i update my service:

Dubbo-go still visits the old address as shown in first picture .

I can only restart the service measured by dubbo-go to restore.

### PR DESCRIPTION
**Pull request by wenxuwan**
**What this PR does**:
try to fix #660

### CODE REVIEW

File: remoting/zookeeper/listener.go [hunk 1]
```diff
@@ -37,6 +37,10 @@ import (
 	"github.com/apache/dubbo-go/remoting"
 )
 
+var (
+	DefaultTTL = 15 * time.Minute
```
Comment (zouyx) [inline remoting/zookeeper/listener.go:41]:
```suggestion
	defaultTTL = 15 * time.Minute
```
I think this is a private variable?

File: remoting/zookeeper/listener.go [hunk 2]
```diff
@@ -197,10 +201,20 @@ func (l *ZkEventListener) listenDirEvent(conf *common.URL, zkPath string, listen
...
 		zkEvent   zk.Event
 	)
 	event = make(chan struct{}, 4)
+	ttl = DefaultTTL
+	if conf != nil {
+		timeout, err := time.ParseDuration(conf.GetParam(constant.REGISTRY_TTL_KEY, constant.DEFAULT_REG_TTL))
+		if err == nil {
+			ttl = timeout
+		} else {
+			logger.Warnf("wrong configuration for registry ttl, error:=%+v", err)
```
[the remark this answers is not in the document]
Comment (wenxuwan) [reply remoting/zookeeper/listener.go]: done

File: remoting/zookeeper/listener.go (hunk 1 above)
Comment (wenxuwan) [reply remoting/zookeeper/listener.go]: Yes, fix finished
