### PR TITLE
Fix:fix url params unsafe

### LINKED ISSUE #200: URL.params concurrent map read and map write problem
**What happened**:
program crash due to URL.params concurrent map read and map write problem

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

A paramsLock (common/url.go baseUrl struct) is introduced in recent commit to fix concurrent map read and write problem of params. However,  this problem has not been completely solved. In  function "MergeUrl", params are set without this lock guard.

### PR DESCRIPTION
**Pull request by hxmhlt**
**What this PR does**:
Fix fix url params unsafe completely.

**Which issue(s) this PR fixes**:

Fixes #200 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: common/url.go [hunk 1]
```diff
@@ -291,20 +293,38 @@ func (c URL) Service() string {
...
+}
+
+func (c *URL) SetParam(key string, value string) {
+	c.paramsLock.Lock()
+	c.params.Set(key, value)
 	c.paramsLock.Unlock()
 }
 
+func (c *URL) RangeParams(f func(key, value string) bool) {
+	c.paramsLock.RLock()
```
Comment (AlexStocks) [inline common/url.go]: use defer unlock pls to defeat the for-loop panic.
