### PR TITLE
fix: nil pointer bug

### LINKED ISSUE #2981: [BUG] 泛化调用报session Already Closed 客户端无法自动恢复
### ✅ Verification Checklist

- [x] 🔍 I have searched the [existing issues](https://github.com/apache/dubbo-go/issues/2739) and confirmed this is not a duplicate

### 🚀 Go Version

1.23.3

### 📦 Dubbo-go Version

v3.3.0

### 💾 Operating System

🍎 macOS

### 📝 Bug Description

closed：k8s 集群provider部署后,客户端访问报session Already Closed 客户端消费者无法自动恢复 #2739 
#2739 没有相关的解决方案
现象：
1. Failed to invoke the method getDeviceInfo in the service xxxx. Tried 2 times of the providers [dubbo://:@10.202.244.89:40110/?interface=xxx&group=&version= dubbo://:@10.202.244.98:40110/?interface=xxx&group=&version= dubbo://:@10.202.244.98:40110/?interface=xxx&group=&version=] (3/2)from the registry zookeeper://10.202.244.31:2181?registry=zookeeper&registry.group=&registry.id=zk&registry.label=true&registry.namespace=&registry.preferred=false&registry.role=0&registry.timeout=10s&registry.ttl=20s&registry.weight=0&registry.zone=&remote-client-name=dubbo.registries-zookeeper-10.202.244.31%3A2181&simplified=false on the consumer 192.168.171.167 using the dubbo version 3.2.0. Last error is session Already Closed.
2. dubbo-getty@v1.4.10/client.go:346打印日志，一直在连接旧的地址：net.DialTimeout(addr:10.202.244.98:40110, timeout:3e+09) = error:dial tcp 10.202.244.98:40110: connect: connection refused\ngithub.com/apache/dubbo-getty.(*client).dialTCP\n\t/root/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.10/client.go:173\ngithub.com/apache/dubbo-getty.(*client).dial\n\t/root/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.10/client.go:346\ngithub.com/apache/dubbo-getty.(*client).connect\n\t/root/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.10/client.go:384\ngithub.com/apache/dubbo-getty.(*client).reConnect\n\t/root/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.10/client.go:441\ngithub.com/apache/dubbo-getty.(*session).stop.func1\n\t/root/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.10/session.go:863\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:78\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:69\ngithub.com/apache/dubbo-getty.(*session).stop\n\t/root/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.10/session.go:853\ngithub.com/apache/dubbo-getty.(*session).handlePackage.func1\n\t/root/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.10/session.go:595\ngithub.com/apache/dubbo-getty.(*session).handlePackage\n\t/root/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.10/session.go:622\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700

### 🔄 Steps to Reproduce

1. 可能服务端频繁重启偶现此情况
2. zk宕机恢复后出现此情况
3. 非频繁重启也会出现此情况

### ✅ Expected Behavior

自动恢复

### ❌ Actual Behavior

无法自动恢复

### 💡 Possible Solution

_No response_

### PR DESCRIPTION
**Pull request by Alanxtl**
fix https://github.com/apache/dubbo-go/issues/2981

1. this bug was introduced in https://github.com/apache/dubbo-go/pull/2726, the operation of `bi.url` set to nil and the access of url in `cluster/cluster/failover/cluster_invoker.go: 86` may happen concurrently, thus cause nil pointer access
```
func (bi *BaseInvoker) Destroy() {
	logger.Infof("Destroy invoker: %s", bi.GetURL())
	bi.destroyed.Store(true)
	bi.available.Store(false)
	bi.url = nil
}
```

2. ivk may be destoryed in line 88 when inovke fails, so when line 90 tries to get its url, the programme panics

### CODE REVIEW

File: cluster/cluster/failover/cluster_invoker.go [hunk 1]
```diff
@@ -85,9 +85,10 @@ func (invoker *failoverClusterInvoker) Invoke(ctx context.Context, invocation pr
 		}
 		invoked = append(invoked, ivk)
 		// DO INVOKE
+		ivkURL := ivk.GetURL().Key()
```
Comment (cjphaha) [inline cluster/cluster/failover/cluster_invoker.go:88]: Is it possible for ivk.GetURL() to be nil? Should check for it?

**Comment by 1kasa** [comment]
Could you provide a test case?

File: cluster/cluster/failover/cluster_invoker.go (hunk 1 above)
Comment (Alanxtl) [reply cluster/cluster/failover/cluster_invoker.go:88]: ivk in this part can't be nil. it is checked in line 83

**Review by cjphaha — APPROVED** [review]
LGTM

**Comment by Alanxtl** [comment]
> Could you provide a test case?

done
