### PR TITLE
Fix: attachments maybe nil or empty string

### LINKED ISSUE #1583: pkg.Unmarshal(len(@data):0) = error:get wrong attachments
**What happened**:

基于 [JSON-PRC](https://github.com/apache/dubbo-go-samples/tree/master/rpc/jsonrpc) 改造入参出参，同 #1582 ，在此代码基础上，Server 同时暴露 `dubbo` 和 `jsonrpc`协议，Client 消费使用 `dubbo`协议时，Server 报错如下：

Server Error Log:
```
2021-11-11T15:14:28.086+0800    ERROR   dubbo/dubbo_codec.go:196        pkg.Unmarshal(len(@data):0) = error:get wrong attachments: 
dubbo.apache.org/dubbo-go/v3/protocol/dubbo/impl.unmarshalRequestBody
        /Users/phil/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.0-rc3.0.20211109121610-2ebc38bed562/protocol/dubbo/impl/hessian.go:267
dubbo.apache.org/dubbo-go/v3/protocol/dubbo/impl.HessianSerializer.Unmarshal
        /Users/phil/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.0-rc3.0.20211109121610-2ebc38bed562/protocol/dubbo/impl/hessian.go:56
dubbo.apache.org/dubbo-go/v3/protocol/dubbo/impl.(*ProtocolCodec).Decode
        /Users/phil/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.0-rc3.0.20211109121610-2ebc38bed562/protocol/dubbo/impl/codec.go:186
dubbo.apache.org/dubbo-go/v3/protocol/dubbo/impl.(*DubboPackage).Unmarshal
        /Users/phil/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.0-rc3.0.20211109121610-2ebc38bed562/protocol/dubbo/impl/package.go:93
dubbo.apache.org/dubbo-go/v3/protocol/dubbo.(*DubboCodec).decodeRequest
        /Users/phil/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.0-rc3.0.20211109121610-2ebc38bed562/protocol/dubbo/dubbo_codec.go:189
dubbo.apache.org/dubbo-go/v3/protocol/dubbo.(*DubboCodec).Decode
        /Users/phil/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.0-rc3.0.20211109121610-2ebc38bed562/protocol/dubbo/dubbo_codec.go:165
dubbo.apache.org/dubbo-go/v3/remoting/getty.(*RpcServerPackageHandler).Read
        /Users/phil/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.0-rc3.0.20211109121610-2ebc38bed562/remoting/getty/readwriter.go:104
github.com/apache/dubbo-getty.(*session).handleTCPPackage
        /Users/phil/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.5/session.go:627
github.com/apache/dubbo-getty.(*session).handlePackage
        /Users/phil/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.5/session.go:549
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1371
dubbo.apache.org/dubbo-go/v3/protocol/dubbo.(*DubboCodec).decodeRequest
        /Users/phil/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.0-rc3.0.20211109121610-2ebc38bed562/protocol/dubbo/dubbo_codec.go:196
dubbo.apache.org/dubbo-go/v3/protocol/dubbo.(*DubboCodec).Decode
        /Users/phil/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.0-rc3.0.20211109121610-2ebc38bed562/protocol/dubbo/dubbo_codec.go:165
dubbo.apache.org/dubbo-go/v3/remoting/getty.(*RpcServerPackageHandler).Read
        /Users/phil/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.0-rc3.0.20211109121610-2ebc38bed562/remoting/getty/readwriter.go:104
github.com/apache/dubbo-getty.(*session).handleTCPPackage
        /Users/phil/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.5/session.go:627
github.com/apache/dubbo-getty.(*session).handlePackage
        /Users/phil/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.5/session.go:549
```
Client dubbogo.yml
```yaml
dubbo:
  consumer:
    references:
      UserProvider:
#        protocol: jsonrpc
        protocol: dubbo
        interface: com.ikurento.user.UserProvider
```

**What you expected to happen**:
Server正常处理请求

**How to reproduce it (as minimally and precisely as possible)**:
-
**Anything else we need to know?**:
-

### PR DESCRIPTION
**Pull request by PhilYue**
**What this PR does**:

Unmarshal request body by `hession.go` , the attribute `attachments` maybe nil or empty string, and will stop the invoked

**Which issue(s) this PR fixes**:

if attachments nil or empty string , default a value that for normal invoking

Fixes #1583 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by PhilYue** [comment]
#1583

**Review by zhaoyunxing92 — APPROVED** [review]

File: protocol/dubbo/impl/hessian.go [hunk 1]
```diff
@@ -254,7 +254,7 @@ func unmarshalRequestBody(body []byte, p *DubboPackage) error {
 		return perrors.WithStack(err)
 	}
 
-	if attachments == nil {
+	if attachments == nil || attachments == "" {
```
Comment (AlexStocks) [inline protocol/dubbo/impl/hessian.go:257]: if len(attachments) == 0 {}

Comment (PhilYue) [reply protocol/dubbo/impl/hessian.go:257]: len 不支持， attachments 类型是 interface{}

**Review by AlexStocks — APPROVED** [review]
