### PR TITLE
fix(cluster/failback): add exponential backoff for retry mechanism

### LINKED ISSUE #3179: [BUG] Failback cluster retry uses fixed 5s interval causing retry storm
### ✅ 验证清单

- [x] 🔍 我已经搜索过 [现有 Issues](https://github.com/apache/dubbo-go/issues)，确信这不是重复问题

### 🚀 Go 版本

1.24+

### 📦 Dubbo-go 版本

v3.3.1

### 🖥️ 服务端配置

_No response_

### 💻 客户端配置

_No response_

### 🌐 协议配置

_No response_

### 📋 注册中心配置

_No response_

### 💾 操作系统

🍎 macOS

### 📝 Bug 描述

`cluster/cluster/failback/cluster_invoker.go` 中的重试逻辑使用固定 5 秒间隔，当大量请求同时失败时，会在 5 秒后同时重试，造成重试风暴。
比如： 100 并发失败 → 5 秒后 100 个同时重试 → 重试风暴
**问题代码** (第 106 行):
```go
retryTask := value.(*retryTimerTask)
if time.Since(retryTask.lastT).Seconds() < 5 {
    break
}
```

### 🔄 重现步骤

1. 启动 dubbo-go 消费者，使用 failback 集群策略
2. 模拟 100 个并发请求同时失败
3. 观察 5 秒后的重试行为

### ✅ 预期行为

多个失败请求的重试时间分散，避免同时重试

### ❌ 实际行为

- 所有失败请求固定等待 5 秒后同时重试
- 100 个并发失败 → 5 秒后 100 个请求同时重试 → 可能再次失败 → 循环

### 💡 可能的解决方案

Failback 用于"可以延迟但必须成功"的场景，指数退避让"延迟"更可控，避免雪崩。

使用 github.com/cenkalti/backoff/v4 为每个重试任务实现独立的指数退避:
```go
type retryTimerTask struct {
    // ...
    nextBackoff    time.Duration
    backoff        *backoff.ExponentialBackOff
}
// 使用动态间隔替代固定 5 秒
if time.Since(retryTask.lastT) < retryTask.nextBackoff {
    break
}
```
模拟 100 个任务同时失败，统计首次重试时间分布：
旧实现 (固定 5s):
所有 100 个任务在第 5 秒同时重试
重试时间分散度: 0ms
新实现 (指数退避 + jitter):
100 个任务的首次重试分散在 500ms ~ 1500ms 范围内
重试时间分散度: ~1000ms

### PR DESCRIPTION
**Pull request by CAICAIIs**
### Summary
Replace the fixed 5-second retry interval in Failback cluster with exponential backoff (1s→60s) to prevent retry storms when downstream services experience extended outages.
### Problem
The current Failback cluster implementation uses a **fixed 5-second interval** for all retry attempts:
```go
if time.Since(retryTask.lastT).Seconds() < 5 {
    break
}
```
This causes retry storm issues in production:
- When a downstream service is down, all failed requests are retried every 5 seconds
- With 100 concurrent failures, the downstream receives 100 retry requests every 5 seconds
- This creates unnecessary pressure on recovering services and delays recovery
### Solution
Implement exponential backoff using github.com/cenkalti/backoff/v4:
| Parameter | Value |
|-----------|-------|
| Initial Interval | 1 second |
| Max Interval | 60 seconds |
| Multiplier | 1.5 (default) |
| Max Elapsed Time | 0 (never timeout) |

Retry interval progression: 1s → 1.5s → 2.25s → 3.4s → 5s → 7.5s → ... → 60s (cap)
### Changes
- Add nextBackoff and backoff fields to retryTimerTask struct
- Replace fixed 5 seconds check with dynamic nextBackoff duration
- Calculate next backoff interval after each retry attempt
- Add info-level logging for retry scheduling
- Update unit tests to reflect new backoff behavior

### Description
Fixes #3179 

### Checklist
- [x] I confirm the target branch is `develop`
- [x] Code has passed local testing
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: cluster/cluster/failback/cluster_test.go [hunk 1]
```diff
@@ -147,14 +149,11 @@ func TestFailbackRetryFailed(t *testing.T) {
...
-	now := time.Now()
 
 	// add retry call that eventually failed.
 	for i := 0; i < retries; i++ {
-		j := i + 1
 		invoker.EXPECT().Invoke(gomock.Any(), gomock.Any()).DoAndReturn(func(context.Context, base.Invocation) result.Result {
-			delta := time.Since(now).Nanoseconds() / int64(time.Second)
-			assert.GreaterOrEqual(t, delta, int64(5*j))
+			// with exponential backoff, retries happen with increasing intervals starting from ~1s
 			wg.Done()
```
Comment (Alanxtl) [inline cluster/cluster/failback/cluster_test.go:157]: 这里指数退避也可以assert时间间隔吧

File: cluster/cluster/failback/cluster_invoker.go [hunk 2]
```diff
@@ -191,25 +196,36 @@ func (t *retryTimerTask) checkRetry() {
 		t.invocation.MethodName(), t.clusterInvoker.GetURL().Service(), t.lastErr)
 	t.retries++
 	t.lastT = time.Now()
-	if t.retries > t.maxRetries {
+	t.nextBackoff = t.backoff.NextBackOff() // calculate next exponential backoff wait time
+
+	if t.retries > t.maxRetries || t.nextBackoff == backoff.Stop {
 		logger.Errorf("Retry times exceed threshold (%v), invocation-> %v.\n",
```
Comment (Alanxtl) [inline cluster/cluster/failback/cluster_invoker.go]:
```suggestion
		logger.Errorf("Retry times exceed threshold (%v), invocation-> %v",
```

File: cluster/cluster/failback/cluster_invoker.go [hunk 3]
```diff
@@ -191,25 +196,36 @@ func (t *retryTimerTask) checkRetry() {
...
 			t.retries, t.invocation)
 		return
 	}
 
+	logger.Infof("Failback retry scheduled after %v for method %v", t.nextBackoff, t.invocation.MethodName())
+
 	if err := t.clusterInvoker.taskList.Put(t); err != nil {
 		logger.Errorf("invoker.taskList.Put(retryTask:%#v) = error:%v", t, err)
 	}
 }
```
Comment (Alanxtl) [inline cluster/cluster/failback/cluster_invoker.go:213]: 是不是应该在put(t)成功之后再更新`t.lastT = time.Now()`,即把198行放到211行之后

**Comment by Alanxtl** [comment]
检查一下会不会出现并发安全的问题，retryTimerTask的retries/lastT/nextBackoff/backoff这几个字段都在变

File: cluster/cluster/failback/cluster_test.go (hunk 1 above)
Comment (CAICAIIs) [reply cluster/cluster/failback/cluster_test.go:157]: 指数间隔有个 Randomization Factor（随机抖动因子），让请求分散，时间断言的话容易引入 flaky test。比如预期 1s，实际可能是 0.8s 或 1.3s

**Comment by CAICAIIs** [comment]
> 检查一下会不会出现并发安全的问题，retryTimerTask的retries/lastT/nextBackoff/backoff这几个字段都在变

应该是没有问题
process() （process也是在单独的 goroutine 中运行）的流程是从队列中取出 task然后检查时间，接着执行重试
任务在队列中时候不会被修改；被取出后只有取出它的 goroutine 在操作；最后放回队列前所有修改已完成（当 task 被 Put 回队列后，下一次取出前不会被其他 goroutine 访问）
