### PR TITLE
Fix: fix revision calc

### LINKED ISSUE #1925: service-discovery-registry failed when set application config
**What happened**:
server config:
``` yml
dubbo:
  application:
    organization: "dubbo"
    name: "game"
    module: "dubbo-go game server"
    version: "0.0.1"
    environment: "dev"
  registries:
    etcd:
      protocol: "etcdv3"
      timeout: "3s"
      address: "127.0.0.1:2379"
      registry-type: service
  metadata-report:
    protocol: etcdv3
    address: 127.0.0.1:2379
  protocols:
    triple:
      name: tri
      port: 20000
  provider:
    services:
      GreeterProvider:
        interface: com.apache.dubbo.sample.basic.IGreeter # must be compatible with grpc or dubbo-java

```

client config:
``` yml
dubbo:
  application:
    organization: "dubbo"
    name: "game"
    module: "dubbo-go game server"
    version: "0.0.1"
    environment: "dev"
  registries:
    etcd:
      protocol: "etcdv3"
      timeout: "3s"
      address: "127.0.0.1:2379"
      registry-type: service
  metadata-report:
    protocol: etcdv3
    address: 127.0.0.1:2379
  protocols:
    triple:
      name: tri
      port: 20000
  provider:
    services:
      GreeterProvider:
        interface: com.apache.dubbo.sample.basic.IGreeter # must be compatible with grpc or dubbo-java

```
client log:
> 2022-06-07T19:53:27.378+0800    INFO    config/config_loader_options.go:200     The following profiles are active: default
2022-06-07T19:53:27.378+0800    INFO    config/root_config.go:129       [Config Center] Config center doesn't start
2022-06-07T19:53:27.381+0800    WARN    prometheus/reporter.go:237      new prometheus reporter with error = listen tcp :9090: bind: address already in use
2022-06-07T19:53:27.381+0800    INFO    etcdv3/service_discovery.go:310 etcd address is: 127.0.0.1:2379,timeout is:3s
2022-06-07T19:53:27.387+0800    INFO    dubbo/dubbo_protocol.go:98      [DUBBO Protocol] Refer service: dubbo://172.22.28.48:38983/org.apache.dubbo.metadata.Metada
taService?application=game&group=game&interface=org.apache.dubbo.metadata.MetadataService&port=38983&protocol=dubbo&release=dubbo-golang-3.0.0&timestamp=1654602800
&version=1.0.0
2022-06-07T19:53:27.387+0800    INFO    etcdv3/listener.go:204  got children list key -> /services/game/172.22.28.48:20000
2022-06-07T19:53:27.387+0800    INFO    etcdv3/listener.go:219  [ETCD Listener] listen dubbo service key{/services/game}
2022-06-07T19:53:30.385+0800    ERROR   config/consumer_config.go:157   No provider available of the service com.apache.dubbo.sample.basic.IGreeter.please check co
nfiguration.
dubbo.apache.org/dubbo-go/v3/config.(*ConsumerConfig).Load
        /home/raynor/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.2/config/consumer_config.go:157
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Start.func1
        /home/raynor/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.2/config/root_config.go:203
sync.(*Once).doSlow
        /home/raynor/sdk/go1.18rc1/src/sync/once.go:68
sync.(*Once).Do

**What you expected to happen**:
expect client call success

**How to reproduce it (as minimally and precisely as possible)**:
reproduce example: https://github.com/ray2011/dubbo-go-samples

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by ray2011**
**What this PR does**: 
fix different revision calc in `service_revision_customizer.go:resolveRevision` and `metadata_info.go:(*MetadataInfo).CalcAndGetRevision`, which make client get empty server metadata.

**Which issue(s) this PR fixes**: 
Fixes #1925

**You should pay attention to items below to ensure your pr passes our ci test**
We do not merge pr with ci tests failed

- [x] All ut passed (run 'go test ./...' in project root)
- [x] After go-fmt ed , run 'go fmt project' using goland.
- [x] Golangci-lint passed, run 'sudo golangci-lint run' in project root.
- [x] After import formatted, (using [imports-formatter](https://github.com/dubbogo/tools#5-how-to-get-imports-formatter) to run 'imports-formatter .' in project root, to format your import blocks, mentioned in [CONTRIBUTING.md](https://github.com/apache/dubbo-go/blob/master/CONTRIBUTING.md) above) 
- [x] Your new-created file needs to have [apache license](https://raw.githubusercontent.com/dubbogo/resources/master/tools/license/license.txt) at the top, like other existed file does.
- [x] All integration test passed. You can run integration test locally (with docker env). Clone our [dubbo-go-samples](https://github.com/apache/dubbo-go-samples) project and replace the go.mod to your dubbo-go, and run 'sudo sh start_integration_test.sh' at root of samples project root. (M1 Slice is not Support)

### CODE REVIEW

**Review by AlexStocks — APPROVED** [review]

File: common/metadata_info.go [hunk 1]
```diff
@@ -87,10 +87,10 @@ func (mi *MetadataInfo) CalAndGetRevision() string {
 	if len(mi.Services) == 0 {
 		return "0"
 	}
-	candidates := make([]string, 8)
+	candidates := make([]string, 0, 8)
 
 	for _, s := range mi.Services {
-		sk := s.ServiceKey
+		sk := s.URL.GetParam(constant.InterfaceKey, "")
```
Comment (sanxun0325) [inline common/metadata_info.go:93]: 获取interfaceKey，变量名sk改一下吧

Comment (ray2011) [reply common/metadata_info.go]: > 获取interfaceKey，变量名sk改一下吧

已修改

**Review by justxuewei — APPROVED** [review]
