### PR TITLE
fix(common): Make URL cloning thread-safe

### LINKED ISSUE #3159: [BUG] dubbo-go 的 common.URL.Clone() 方法有并发问题，会导致程序崩溃
### ✅ 验证清单

- [x] 🔍 我已经搜索过 [现有 Issues](https://github.com/apache/dubbo-go/issues)，确信这不是重复问题

### 🚀 Go 版本

1.25.5

### 📦 Dubbo-go 版本

v3.3.1

### 🖥️ 服务端配置

_No response_

### 💻 客户端配置

_No response_

### 🌐 协议配置

_No response_

### 📋 注册中心配置

_No response_

### 💾 操作系统

🍎 macOS

### 📝 Bug 描述

客户端程序运行调用 triple 协议，服务会崩溃，报错「fatal error: concurrent map writes」

### 🔄 重现步骤

```
func TestClone(t *testing.T) {
	u1, _ := NewURL("dubbo://127.0.0.1:20000/com.ikurento.user.UserProvider?interface=com.ikurento.user.UserProvider&group=&version=2.6.0&configVersion=1.0")

	u1.SetAttribute("hello", "world")

	for i := 0; i < 1000; i++ {
		go func() {
			u1.Clone()
		}()
	}
	time.Sleep(2 * time.Second)
}
```

执行 `go test -trimpath -race -v -run TestClone  -timeout 30s | head -n 100`

运行结果

```
=== RUN   TestClone
==================
WARNING: DATA RACE
Write at 0x00c0000a1920 by goroutine 34:
  runtime.mapaccess2_faststr()
      internal/runtime/maps/runtime_faststr_swiss.go:162 +0x29c
  dubbo.apache.org/dubbo-go/v3/common.(*URL).SetAttribute()
      dubbo.apache.org/dubbo-go/v3/common/url.go:568 +0x100
  dubbo.apache.org/dubbo-go/v3/common.(*URL).Clone.func2()
      dubbo.apache.org/dubbo-go/v3/common/url.go:883 +0x4c
  dubbo.apache.org/dubbo-go/v3/common.(*URL).RangeAttributes()
      dubbo.apache.org/dubbo-go/v3/common/url.go:893 +0x144
  dubbo.apache.org/dubbo-go/v3/common.(*URL).Clone()
      dubbo.apache.org/dubbo-go/v3/common/url.go:882 +0x148
  dubbo.apache.org/dubbo-go/v3/common.TestClone.func1()
      dubbo.apache.org/dubbo-go/v3/common/url_test.go:421 +0x2c
```

### ✅ 预期行为

代码正常运行，无并发问题。

### ❌ 实际行为

提示 Data Race，有并发问题。

### 💡 可能的解决方案

修复 Clone() 逻辑，去掉 copier.Copy() 的浅拷贝，通过加锁和直接赋值避免 map 的浅拷贝。

### PR DESCRIPTION
**Pull request by phpcyy**
This commit fixes a critical thread-safety issue in the Clone and CloneExceptParams methods of the URL struct.

The previous implementation used the github.com/jinzhu/copier library, which is not safe for types containing mutexes. This caused two main problems in a concurrent environment:

1. Data Races: The library read fields from the source URL without acquiring a lock, leading to data races.
2. Mutex Copying: The sync.RWMutex fields within the URL were being copied, which is an incorrect usage of mutexes and leads to unpredictable behavior.

The implementation has been refactored to manually construct a new URL instance and explicitly copy each field. This new approach ensures that a cloned URL has its own new, properly initialized mutexes, making the cloning operation safe for concurrent use. This also has the added benefit of removing the copier dependency.

### Description
Fixes #3159

### Checklist
- [x] I confirm the target branch is `develop`
- [x] Code has passed local testing
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Alanxtl** [comment]
what about add test cases to test these `clone`

File: common/url.go [hunk 1]
```diff
@@ -869,20 +875,38 @@ func (c *URL) MergeURL(anotherUrl *URL) *URL {
 
 // Clone will copy the URL
 func (c *URL) Clone() *URL {
```
Comment (AlexStocks) [inline common/url.go]:
```go
// CloneWithFilter - Clone the URL with parameter filtering
// excludeParams: the set of parameters to exclude from the cloned URL
// reserveParams: the set of parameters to retain in the cloned URL
func (c *URL) CloneWithFilter(excludeParams *gxset.HashSet, reserveParams []string) *URL {
    newURL := &URL{
        Protocol:     c.Protocol,
        Location:     c.Location,
        Ip:           c.Ip,
        Port:         c.Port,
        PrimitiveURL: c.PrimitiveURL,
        Path:         c.Path,
        Username:     c.Username,
        Password:     c.Password,
        Methods:      append(make([]string, 0), c.Methods...),
        attributes:   make(map[string]any),
        params:       url.Values{},
    }

    // Copy and filter params based on excludeParams or reserveParams
    c.RangeParams(func(key, value string) bool {
        // If the param is in excludeParams or not in reserveParams, skip it
        if (excludeParams != nil && excludeParams.Contains(key)) || 
           (len(reserveParams) > 0 && !contains(reserveParams, key)) {
            return true
        }
        // Set the param if it passes the filter
        newURL.SetParam(key, value)
        return true
    })

    // Copy attributes
    c.RangeAttributes(func(key string, value any) bool {
        newURL.SetAttribute(key, value)
        return true
    })

    // Copy SubURL if it exists
    if c.SubURL != nil {
        newURL.SubURL = c.SubURL.Clone()
    }

    return newURL
}

// Clone - Clone all contents including params and attributes
func (c *URL) Clone() *URL {
    return c.CloneWithFilter(nil, nil) // No exclusion or reservation, clone everything
}

// CloneExceptParams - Clone all contents, but exclude params in excludeParams
func (c *URL) CloneExceptParams(excludeParams *gxset.HashSet) *URL {
    return c.CloneWithFilter(excludeParams, nil) // Only exclude specified params
}

// CloneWithParams - Clone and keep only the specified params
func (c *URL) CloneWithParams(reserveParams []string) *URL {
    return c.CloneWithFilter(nil, reserveParams) // Only keep specified params
}

// Helper function: Check if a slice contains a specific element
func contains(slice []string, item string) bool {
    for _, v := range slice {
        if v == item {
            return true
        }
    }
    return false
}
```

原代码重复部分太多，请使用新代码

File: common/url.go [hunk 2]
```diff
@@ -869,20 +875,38 @@ func (c *URL) MergeURL(anotherUrl *URL) *URL {
...
-		newURL.SetParam(key, value)
-		return true
-	})
-	c.RangeAttributes(func(key string, value any) bool {
-		newURL.SetAttribute(key, value)
-		return true
-	})
+
 	return newURL
 }
```
[the remark this answers is not in the document]
Comment (phpcyy) [reply common/url.go]: done

File: common/url.go [hunk 3]
```diff
@@ -897,18 +921,41 @@ func (c *URL) RangeAttributes(f func(key string, value any) bool) {
...
+			return true
+		},
+	)
+
+	if c.SubURL != nil {
+		newURL.SubURL = c.SubURL.Clone()
+	}
+
 	return newURL
 }
```
[the remark this answers is not in the document]
Comment (phpcyy) [reply common/url.go:944]: done

File: common/url.go (hunk 1 above)
Comment (phpcyy) [reply common/url.go]: done

**Comment by phpcyy** [comment]
> Since the “github.com/jinzhu/copier” dependency has been removed, why hasn't the go.mod file changed? There shouldn't be any other code still using this library.

I have updated the go.mod file and delete extra dependencies.

File: common/url.go [hunk 4]
```diff
@@ -867,25 +874,61 @@ func (c *URL) MergeURL(anotherUrl *URL) *URL {
...
-// Clone will copy the URL
-func (c *URL) Clone() *URL {
-	newURL := &URL{}
-	if err := copier.Copy(newURL, c); err != nil {
-		// this is impossible
-		return newURL
+// CloneWithFilter - Clone the URL with parameter filtering
+// excludeParams: the set of parameters to exclude from the cloned URL
+// reserveParams: the set of parameters to retain in the cloned URL
+func (c *URL) CloneWithFilter(excludeParams *gxset.HashSet, reserveParams []string) *URL {
```
Comment (AlexStocks) [inline common/url.go:880]: 给这几个 Clone 函数也都添加一些 ut 吧

**Review by No-SilverBullet — APPROVED** [review]
LGTM
