### PR TITLE
fix: #1320 泛化调用+应用级服务发现，客户端 panic

### LINKED ISSUE #1320: 泛化调用+应用级服务发现，客户端 panic
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

### LINKED ISSUE #1325: 1.5 local模式的应用级别服务发现，打印error日志
选择dynamic mapping会报配置中心 zk node节点 dubbo/config 不存在的error
因为用户只需要配置中心做源数据上报，不需要拉取配置，只需要报warning即可。

### PR DESCRIPTION
**Pull request by LaurenceLiZhixin**
**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #1320 
Fixes #1325 
增加了generic client 必要的启动逻辑，确保不会panic
修改配置中心初始化时错误的日志为warning

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: config/reference_config.go [hunk 1]
```diff
@@ -281,6 +281,8 @@ func (c *ReferenceConfig) getUrlMap() url.Values {
 
 // GenericLoad ...
```
Comment (AlexStocks) [inline config/reference_config.go:282]: add remark for this func.

Comment (LaurenceLiZhixin) [reply config/reference_config.go]: fixed

**Review by cityiron — APPROVED** [review]

**Review by AlexStocks — APPROVED** [review]
