### PR TITLE
Fix: fix bug when creating metrics objects concurrently

### LINKED ISSUE #1953: Prometheus reporters fail to prevent creating concurrently
**What happened:**
When I want to collect custom metrics in filter, some metrics never changed. I think it may be caused by concurrent creation of metrics objects, the code tries to use syncMap's Load to avoid duplicate creation, but this is useless. 
https://github.com/apache/dubbo-go/blob/b7e348319f82444e18ecda284e20656d7ed3b861/metrics/prometheus/reporter.go#L296-L309
When I debug, I find that the Register() returns an AlreadyExist error, but this error is incorrectly ignored

**What you expected to happen:**
The same metrics object should be created only once and needs to be guaranteed to be registered successfully.

**How to reproduce it (as minimally and precisely as possible):**
image

**Anything else we need to know?:**
In addition to counter, metrics such as Gauge should also have this problem

### PR DESCRIPTION
**Pull request by CoolIceV**
**What this PR does**: 
fix bug when creating metrics objects concurrently

**Which issue(s) this PR fixes**: 
Fixes #1953 

**You should pay attention to items below to ensure your pr passes our ci test**
We do not merge pr with ci tests failed

- [ ] All ut passed (run 'go test ./...' in project root)
- [ ] After go-fmt ed , run 'go fmt project' using goland.
- [ ] Golangci-lint passed, run 'sudo golangci-lint run' in project root.
- [ ] After import formatted, (using [imports-formatter](https://github.com/dubbogo/tools#5-how-to-get-imports-formatter) to run 'imports-formatter .' in project root, to format your import blocks, mentioned in [CONTRIBUTING.md](https://github.com/apache/dubbo-go/blob/master/CONTRIBUTING.md) above) 
- [ ] Your new-created file needs to have [apache license](https://raw.githubusercontent.com/dubbogo/resources/master/tools/license/license.txt) at the top, like other existed file does.
- [ ] All integration test passed. You can run integration test locally (with docker env). Clone our [dubbo-go-samples](https://github.com/apache/dubbo-go-samples) project and replace the go.mod to your dubbo-go, and run 'sudo sh start_integration_test.sh' at root of samples project root. (M1 Slice is not Support)

### CODE REVIEW

**Review by AlexStocks — APPROVED** [review]

File: metrics/prometheus/reporter.go [hunk 1]
```diff
@@ -253,10 +253,16 @@ func (reporter *PrometheusReporter) setGauge(gaugeName string, toSetValue float6
 		// gauge
 		if val, exist := reporter.userGauge.Load(gaugeName); !exist {
 			newGauge := newGauge(gaugeName, reporter.namespace)
```
Comment (Mulavar) [inline metrics/prometheus/reporter.go:255]: maybe it's better to use other variable names to avoid confusion

**Review by justxuewei — APPROVED** [review]

**Comment by AlexStocks** [comment]
@Mulavar pls review agaiin.

**Review by Mulavar — APPROVED** [review]
