### PR TITLE
fix client block until timeout when provider return with PackageResponse_Exception

### LINKED ISSUE #925: client will block until timeout when provider return with PackageResponse_Exception
image

As the picture shown, when provider return with PackageResponse_Exception, the client will block until timeout

image

### PR DESCRIPTION
**Pull request by wenxuwan**
try to fix #925

### CODE REVIEW

**Review by zouyx — APPROVED** [review]

**Review by AlexStocks — APPROVED** [review]

**Comment by AlexStocks** [comment]
@wenxuwan pls change ur pr title to let users know what this pr do when release 1.5.5

**Comment by wenxuwan** [comment]
> @wenxuwan pls change ur pr title to let users know what this pr do when release 1.5.5

done

File: protocol/dubbo/impl/codec.go [hunk 1]
```diff
@@ -163,15 +163,12 @@ func (c *ProtocolCodec) Decode(p *DubboPackage) error {
 	if p.IsResponseWithException() {
 		logger.Infof("response with exception: %+v", p.Header)
 		decoder := hessian.NewDecoder(body)
+		p.Body = &ResponsePayload{}
```
Comment (fangyincheng) [inline protocol/dubbo/impl/codec.go:166]: why？

**Review by fangyincheng — DISMISSED** [review]

File: protocol/dubbo/impl/codec.go (hunk 1 above)
Comment (wenxuwan) [reply protocol/dubbo/impl/codec.go:166]: here, p.Body also be nil, so will return perrors.Errorf("java exception:%s", exception.(string)), this will cause the client timeout always.

**Review by fangyincheng — APPROVED** [review]
