### PR TITLE
Fix: fix the exception when tcp timeout is less than 1s for 3.0 #1362

### LINKED ISSUE #1362: getty 偶现panic，程序退出
**What happened**:
使用dubbo-go的程序会异常退出

**What you expected to happen**:
如果发生异常，能通过recover捕获异常。
**How to reproduce it (as minimally and precisely as possible)**:
偶现的，我也不知道怎么重现问题
**Anything else we need to know?**:
一些错误提示：
``
2021-08-03T07:25:46.724+0100  DEBUG  getty/pool.go:195  add session{session {client:TCP_CLIENT:24:10.0.2.15:34697<->172.31.229.155:20889}, Read Bytes: 0, Write Bytes: 0, Read Pkgs: 0, Write Pkgs: 0}
2021-08-03T07:25:46.724+0100  ERROR  getty/pool.go:157  tcpConn.SetKeepAlivePeriod() = error:%vset tcp 10.0.2.15:43983->172.31.40.48:28089: setsockopt: invalid argument
github.com/apache/dubbo-go/remoting/getty.(*gettyRPCClient).newSession
  /golang/monitor-agent/vendor/github.com/apache/dubbo-go/remoting/getty/pool.go:157
github.com/apache/dubbo-getty.(*client).connect
  /golang/monitor-agent/vendor/github.com/apache/dubbo-getty/client.go:391
github.com/apache/dubbo-getty.(*client).reConnect
  /golang/monitor-agent/vendor/github.com/apache/dubbo-getty/client.go:443
github.com/apache/dubbo-getty.(*client).RunEventLoop
  /golang/monitor-agent/vendor/github.com/apache/dubbo-getty/client.go:421
panic: @rTimeout < 1

goroutine 6331 [running]:
github.com/apache/dubbo-getty.(*gettyConn).SetReadTimeout(0xc000b5e410, 0x0)
  /golang/monitor-agent/vendor/github.com/apache/dubbo-getty/connection.go:118 +0x65
github.com/apache/dubbo-go/remoting/getty.(*gettyRPCClient).newSession(0xc00017e000, 0x12436d0, 0xc0004569c0, 0x12436d0, 0xc0004569c0)
  /golang/monitor-agent/vendor/github.com/apache/dubbo-go/remoting/getty/pool.go:171 +0x892
github.com/apache/dubbo-getty.(*client).connect(0xc000a61040)
  /golang/monitor-agent/vendor/github.com/apache/dubbo-getty/client.go:391 +0xa4
github.com/apache/dubbo-getty.(*client).reConnect(0xc000a61040)
  /golang/monitor-agent/vendor/github.com/apache/dubbo-getty/client.go:443 +0x56
github.com/apache/dubbo-getty.(*client).RunEventLoop(0xc000a61040, 0xc000254410)
  /golang/monitor-agent/vendor/github.com/apache/dubbo-getty/client.go:421 +0x6d
created by github.com/apache/dubbo-go/remoting/getty.newGettyRPCClientConn
  /golang/monitor-agent/vendor/github.com/apache/dubbo-go/remoting/getty/pool.go:82 +0x22b
``
dubbo-go v1.5.6和v3.0.0都有这个问题

### PR DESCRIPTION
**Pull request by ChangedenCZD**
**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #1362

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

File: remoting/getty/config.go [hunk 1]
```diff
@@ -162,13 +162,18 @@ func (c *GettySessionParam) CheckValidity() error {
 		return perrors.WithMessagef(err, "time.ParseDuration(KeepAlivePeriod{%#v})", c.KeepAlivePeriod)
 	}
 
-	if c.tcpReadTimeout, err = time.ParseDuration(c.TcpReadTimeout); err != nil {
+	var tcpTimeout *time.Duration
+	tcpTimeoutMinVal := time.Second * 1
```
Comment (AlexStocks) [inline remoting/getty/config.go:166]: this should be a file-scope global var.

Comment (ChangedenCZD) [reply remoting/getty/config.go]: Done

**Review by AlexStocks — APPROVED** [review]

**Comment by Mulavar** [comment]
与 1.5 分支同样问题

File: remoting/getty/config.go [hunk 2]
```diff
@@ -177,6 +182,23 @@ func (c *GettySessionParam) CheckValidity() error {
 	return nil
 }
 
+func parseTimeDurationByRange(timeStr string, min *time.Duration, max *time.Duration) (time.Duration, error) {
+	result, err := time.ParseDuration(timeStr)
+	if err != nil {
+		return *min, err
+	}
+	if min != nil && max != nil && *min > *max { // swap
```
Comment (xavier-niu) [inline remoting/getty/config.go:190]: IMO, if the value is invalid, the program should go crash to make the user realize something goes wrong, instead of swapping without any warning.

File: remoting/getty/config.go [hunk 3]
```diff
@@ -177,6 +182,23 @@ func (c *GettySessionParam) CheckValidity() error {
 	return nil
 }
 
+func parseTimeDurationByRange(timeStr string, min *time.Duration, max *time.Duration) (time.Duration, error) {
```
Comment (xavier-niu) [inline remoting/getty/config.go:185]: What if the value of `min` or  the `max` is less than 0? The boundary conditions should be fully considered.

**Review by ztelur — APPROVED** [review]

**Review by zouyx — APPROVED** [review]
