### PR TITLE
fix issue #207: common/utils/net_test.go:25 cannot pass

### LINKED ISSUE #207: common/utils/net_test.go:25 cannot pass
We should refer to com.alibaba.dubbo.common.utils.NetUtils#getLocalAddress to enhance the logic for fetching the local address.

### PR DESCRIPTION
**Pull request by beiwei30**
**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #207 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: common/utils/net.go [hunk 1]
```diff
@@ -39,38 +40,49 @@ func init() {
...
-				ip = v.IP
-			}
 
-			if !ip.IsLoopback() && ip.To4() != nil && isPrivateIP(ip.String()) {
-				ipAddr = ip
-				break
+		if ipv4, ok := getValidIPv4(addrs); ok {
+			ipv4Addr = ipv4
+			if isPrivateIP(ipv4.String()) {
+				privateIpv4Addr = ipv4
```
Comment (wongoo) [inline common/utils/net.go]: just return here

File: common/utils/net.go [hunk 2]
```diff
@@ -39,46 +40,86 @@ func init() {
 
 // ref: https://stackoverflow.com/questions/23558425/how-do-i-get-the-local-ip-address-in-go
```
Comment (AlexStocks) [inline common/utils/net.go]: pls delete this ref. thx.
